defaults:
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
connection:
  host_name: cse.unsw.edu.au
  username: z5380598
  private_key: /Users/z5380598/.ssh/tutoring
  use_pass: False
paths:
  known_hosts: /Users/z5380598/.ssh/known_hosts
  local_labs_path: /Users/z5380598/UNSW/Tutorial/cs3331/24T1
  remote_path: /home/cs3331/
  auto_outputs_dir: outputs
marking:
  term: 24T1
  class_names: ["thu11-organ", "thu13-organ", "thu15-bass"]
  assign: False
  deadline:
    cur: "2024/02/03 00:00:00"
    # This is in minutes, 1440 min = 1 day
    thresholds: [180, 1500, 2940, 4380, 5840, 7260, 8700, 10080]
    lab_penalties: [0, 5, 10, 15]
    assign_penalties: [0, 5, 10, 15]
  auto:
    lab2:
      port_num: 12000

hydra:
  job:
    # prevent switching directories when running functions
    chdir: False
    env_set:
      # enable printing full stack trace
      HYDRA_FULL_ERROR: 1
  # hydra to disable creating output folders
  output_subdir: null
  run:
    dir: .
  job_logging:
    formatters:
      colorlog:
        datefmt: '%d-%m-%y %H:%M:%S'
    root:
      level: INFO
      handlers: [ console ]